name: Deploy Datafile (Prod)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATAFILE_ID: rudy
      DATAFILE_LANG: pl

      # generate
      DATAFILE_QUALITY: 1

      # upload
      DATAFILE_POSITION: 1

    steps:
      - name: Checkout database-tools
        uses: actions/checkout@v3
        with:
          repository: bartekpacia/database-tools
          token: ${{ secrets.DATABASE_TOOLS_TOKEN }}

      - name: Checkout datafile repo
        uses: actions/checkout@v3
        with:
          repository: bartekpacia/datafile-rudy
          path: "datafiles/datafile-rudy"

      - name: Create service account file
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > ./key.json

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install database-tools
        run: make

      - name: print imagemagick version
        run: magick --version && convert --version

      - run: /usr/bin/convert /home/runner/work/datafile-rudy/datafile-rudy/datafiles/datafile-rudy/sections/attractions/places/boisko/images/compressed/ic_boisko.webp -quality 60% -resize 128x128 /home/runner/work/datafile-rudy/datafile-rudy/generated/rudy/images/mini_ic_boisko.webp

      - name: Generate datafile
        run: ./touristdb generate -id $DATAFILE_ID --lang $DATAFILE_LANG --quality $DATAFILE_QUALITY -v

      - name: Compress datafile
        run: ./touristdb compress -id $DATAFILE_ID --verbose

      - name: Upload datafile
        run: ./touristdb upload -id $DATAFILE_ID --position $DATAFILE_POSITION --verbose
