name: deploy tst

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy datafile
        uses: otwartaturystyka/deploy-datafile-action@v1
        with:
          id: rudy
          position: 1
          prod: false
          service-account-key-base64: ${{ secrets.SERVICE_ACCOUNT_KEY_BASE64 }}
