name: Deploy Datafile (Prod)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATAFILE_ID: rudy
      DATAFILE_LANG: pl

      # generate
      DATAFILE_QUALITY: 1

      # upload
      DATAFILE_POSITION: 1

    steps:
      - name: Checkout database-tools
        uses: actions/checkout@v2
        with:
          repository: bartekpacia/database-tools
          token: ${{ secrets.DATABASE_TOOLS_TOKEN }}

      - name: Checkout datafile repo
        uses: actions/checkout@v2
        with:
          repository: bartekpacia/datafile-rudy
          path: "datafiles/datafile-rudy"

      - name: Create service account file
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > ./key.json

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install database-tools
        run: make

      - name: Generate datafile
        run: ./touristdb generate -id $DATAFILE_ID --lang $DATAFILE_LANG -q $DATAFILE_QUALITY -v

      - name: Compress datafile
        run: ./touristdb compress -id $DATAFILE_ID -v

      - name: Upload datafile
        run: ./touristdb upload -id $DATAFILE_ID -pos $DATAFILE_POSITION -v
