name: Deploy Tst

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # generate, compress, upload
      DATAFILE_ID: rudy

      # generate
      DATAFILE_QUALITY: 1
      DATAFILE_LANG: pl

      # compress
      # no arguments currently

      # upload
      DATAFILE_POSITION: 1

    steps:
      - name: Checkout database-tools
        uses: actions/checkout@v3
        with:
          repository: bartekpacia/database-tools
          token: ${{ secrets.DATABASE_TOOLS_TOKEN }}

      - name: Checkout datafile repo
        uses: actions/checkout@v3
        with:
          repository: bartekpacia/datafile-rudy
          path: "datafiles/datafile-rudy"
          lfs: true

      - name: Create service account file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: "."
          fileName: key.json
          encodedString: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install database-tools
        run: make

      - name: print convert version
        run: convert --version

      - name: Generate datafile
        run: ./touristdb generate -id $DATAFILE_ID --lang $DATAFILE_LANG --quality $DATAFILE_QUALITY -v

      - name: Compress datafile
        run: ./touristdb compress -id $DATAFILE_ID --verbose

      - name: Upload datafile
        run: echo "y" | ./touristdb upload -id $DATAFILE_ID --position $DATAFILE_POSITION
