name: Deploy Prod

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATAFILE_ID: rudy
      DATAFILE_LANGUAGE: pl
      DATAFILE_POSITION: 1

    steps:
      - name: Checkout database-tools
        uses: actions/checkout@v3
        with:
          repository: opentouristics/database-tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout datafile repo
        uses: actions/checkout@v3
        with:
          repository: opentouristics/datafile-${{ env.DATAFILE_ID }}
          path: datafiles/datafile-${{ env.DATAFILE_ID }}
          lfs: true

      - name: Create service account file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: "."
          fileName: key.json
          encodedString: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install database-tools
        run: make

      - name: publish
        run: ./publish "$DATAFILE_ID" "$DATAFILE_LANGUAGE" "$DATAFILE_POSITION" --prod
