name: prepare

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Enforce max line length of text files to 80
        run: test -z $(grep  -l '.\{81,\}' -R . --include='*.txt' || true)
